#!/usr/bin/env bash
#configure domain and subdomain

#my domain name
DOMAIN="makterince.tech"

#config with ip
SUBDOMAINS=(
	"www:${DOMAIN}:${LB_IP}"
	"lb-01:${DOMAIN}:${LB_IP}"
	"web-01:${DOMAIN}:${WEB_01_IP}"
	"web-02:${DOMAIN}:${WEB_02_IP}"
)


display_dom() {
	 # Extract the subdomain, record type, and destination from the dig command output
	 subdomain="$1"
	 domain="$2"
	 rec=$(dig "${subdomain}.${domain}" | awk '/IN/ { print $4 }')
	 ip_add=$(dig "${subdomain}.${domain}" | awk '/IN/ { print $5 }')
	 echo "The subdomain ${subdomain} is a ${rec} record and points to ${ip_add}"
}

#Displays the record and destination when the args are less or equal to two
if [ $# -eq 2 ]
then
	display_dom "$1" "$2"
else
	# If only domain is provided, display information for all subdomains in the SUBDOMAINS array
	for sub in "${SUBDOMAINS[@]}"; do
		IFS=':' read -ra sub_parts <<< "${sub}"
		display_dom "${sub_parts[0]}" "${sub_parts[1]}"
	done
fi
