#!/usr/bin/env bash
# Installs nginx server
apt-get update -y
apt-get install nginx -y
service nginx start
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
