#!/usr/bin/env bash
# Update package list
apt-get update
apt-get install -y nginx
service nginx start
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
