#!/usr/bin/env bash
#making second server identical to the first
sudo apt update
sudo apt install nginx
echo "add_header X-Served-By $(hostname);" | sudo tee /etc/nginx/conf.d/custom_http_response_header.conf > /dev/null
sudo systemctl restart nginx
