#!/usr/bin/env bash
# This script installs and configures HAProxy load balancer
sudo apt-get -y install --no-install-recommends software-properties-common
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo -e '\nfrontend haproxy-main\n\tbind :80\n\tdefault_backend nginx_webservers' >> /etc/haproxy/haproxy.cfg
sudo echo -e '\nbackend nginx_webservers\n\tserver server1 54.165.197.124\n\tserver server2 54.234.35.46' >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
