#!/usr/bin/env bash
# using a while loop and an if condition

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    count=$((count+1))
done
