#!/usr/bin/env bash
#scripts displays content in current directory
for file in *
do
    if [ "${file:0:1}" != "." ] && [ -f "$file" ]; then
        filename=$(echo $file | cut -d'-' -f2-)
        echo "$filename"
    fi
done
